name: Build Flutter APK

on:
  push:
    branches:
      - dev-branch  # Trigger action on push to the 'main' branch (you can change this)
  pull_request:
    branches:
      - dev-branch  # Trigger action on pull requests to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest  # The virtual machine where the build will run

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.0'  # Specify your desired Flutter version here

      # Step 3: Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Step 4: Build the APK (debug or release)
      - name: Build APK
        run: flutter build apk --release  # Use --debug or --release based on your needs

      # Step 5: Upload the APK as an artifact (optional, to download the APK later)
      - name: Upload APK artifact
        uses: actions/upload-artifact@v2
        with:
          name: flutter-apk
          path: build/app/outputs/flutter-apk/*.apk

      # Optional: Optionally, you can also add steps to send the APK via email, upload it to Firebase, etc.
